serv1:
  image: node:7.7.1
  command: npm run build
  working_dir: /app
  volumes:
    - ./server:/app
  environment:
    PORT: 3000
    CONNECTION_STRING_DEV: mongodb://localhost/flypatron
  ports:
    - "3000:3000"
  links:
    - db

db:
  image: mongo
  expose:
    - 27017
  ports:
    - "27017:27017"
